services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.22
        
  postgis:
    #build: ./config/postgis
    image: pgrouting/pgrouting:16-3.5-main
    container_name: postgis
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: 0.0.0.0/0
      FORCE_SSL: "FALSE"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.10
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    expose:
      - "5050"
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.20

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    environment:
      - "CORS_ENABLED=true"
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=500M
      - MAXIMUM_MEMORY=1G
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - ROOT_WEBAPP_REDIRECT=true
      - TOMCAT_EXTRAS=false
      - SAMPLE_DATA=false
      # Extensions set to be installed
      - "INSTALL_EXTENSIONS=true"
      - STABLE_EXTENSIONS=css-plugin,importer-plugin,wmts-multi-dimensional-plugin
      - COMMUNITY_EXTENSIONS=ogcapi-plugin,wmts-styles-plugin
    expose:
      - "8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_bal:/opt/geoserver/data_dir/_BAL_
      - geoserver_settings:/settings
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.11

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: always
    expose:
      - "8081"
    environment:
      - PUID=1000
      - PGID=1000
      - FB_BASEURL=/data
    volumes:
      - postgis_data:/data/postgis
      - geoserver_data:/data/geoserver
      - geoserver_styles:/data/geoserver/styles
      - osm_data:/data/osm
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.21

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./config/homepage:/app/config
      - homepage-public:/app/public
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.16

  mviewer:
    image: mviewer/mviewer
    container_name: mviewer
    restart: always
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.17
    volumes:
      - mviewer_config:/config
      - mviewer_data:/var/www/html/data
    ports:
      - "9091"

  mapstore2:
    image: geosolutionsit/mapstore2
    container_name: ${COMPOSE_PROJECT_NAME}_mapstore2
    restart: always
    depends_on:
      - geoserver
    expose:
      - "8081"
    environment:
      GEOSERVER_URL: http://geoserver:8080/geoserver
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.14

  elasticsearch:  
    image: elasticsearch:7.8.1  
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch  
    expose:  
      - "9200"  
    environment:  
      discovery.type: 'single-node'  
      xpack.security.enabled: 'true'  
      ELASTIC_PASSWORD: 'ensgpassword'  
    networks:  
      sdi_apps:  
        ipv4_address: 172.24.0.23

  kibana:  
    image: kibana:7.8.1  
    container_name: ${COMPOSE_PROJECT_NAME}_kibana  
    volumes:  
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml  
    expose:  
      - "5601"  
    networks:  
      sdi_apps:  
        ipv4_address: 172.24.0.15

  pg_tileserv:
    image: pramsey/pg_tileserv
    container_name: ${COMPOSE_PROJECT_NAME}_pg_tileserv
    expose:
      - "7800"
    restart: always
    depends_on:
      - postgis
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis:5432/ensgdb
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.24

  tegola:
    image: gospatial/tegola
    container_name: ${COMPOSE_PROJECT_NAME}_tegola
    restart: always
    depends_on:
      - pg_tileserv
    expose:
      - "9090"
    volumes:
      - ./config/tegola:/etc/tegola
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.25

volumes: 
  portainer_data:
  postgis_data:
  pgadmin_data:
  geoserver_data:
  geoserver_bal:
  geoserver_settings:
  geoserver_styles:
  osm_data:
  homepage-public:
  mviewer_config:
  mviewer_data:

networks:
  sdi_apps:
    #name: sdi_apps
    external: true
