services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.22
        
  postgis:
    #build: ./config/postgis
    image: pgrouting/pgrouting:16-3.5-main
    container_name: postgis
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: 0.0.0.0/0
      FORCE_SSL: "FALSE"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.10
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    expose:
      - "5050"
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.20

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    environment:
      - "CORS_ENABLED=true"
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=500M
      - MAXIMUM_MEMORY=1G
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - ROOT_WEBAPP_REDIRECT=true
      - TOMCAT_EXTRAS=false
      - SAMPLE_DATA=false
      # Extensions set to be installed
      - "INSTALL_EXTENSIONS=true"
      - STABLE_EXTENSIONS=css-plugin,importer-plugin,wmts-multi-dimensional-plugin
      - COMMUNITY_EXTENSIONS=backup-restore-plugin,ogcapi-plugin,smart-data-loader-plugin,wmts-styles-plugin
    expose:
      - "8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_bal:/opt/geoserver/data_dir/_BAL_
      - geoserver_settings:/settings
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.11

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: always
    expose:
      - "8081"
    environment:
      - PUID=1000
      - PGID=1000
      - FB_BASEURL=/data
    volumes:
      - postgis_data:/data/postgis
      - geoserver_data:/data/geoserver
      - geoserver_styles:/data/geoserver/styles
      - osm_data:/data/osm
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.21

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./config/homepage:/app/config
      - homepage-public:/app/public
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.16
'''
  mviewer:
    image: mviewer/mviewer
    container_name: mviewer
    restart: always
    networks:
      sdi_apps:
        ipv4_address: 192.168.1.13
    volumes:
      - mviewer_config:/config
      - mviewer_data:/var/www/html/data
    ports:
      - "9091"
'''
volumes: 
  portainer_data:
  postgis_data:
  pgadmin_data:
  geoserver_data:
  geoserver_bal:
  geoserver_settings:
  geoserver_styles:
  osm_data:
  homepage-public:
  #mviewer_config:
  #mviewer_data:

networks:
  sdi_apps:
    #name: sdi_apps
    external: true
