---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:
    - Postgis:
        href: http://172.24.0.10:5432
    - PgAdmin:
        href: http://172.24.0.20:/browser
    - Portainer:
        href: http://172.24.0.22:9000
    - Geoserver:
        href: http://172.24.0.11:8080/geoserver
    - FileBrowser:
        href: http://172.24.0.21:8080/data/files/
    - MViewer:
        href: http://172.24.0.17:9091
    - MapStore2:
        href: http://172.24.0.14:8080/mapstore